language: node_js
node_js:
  - "0.12"
  - "iojs"
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
    # remove when https://github.com/mapbox/node-sqlite3/issues/487 is fixed
